### ISSUE TITLE
enzyme database

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1001]
To do for researchers:

- [x] decide on a name, in both text format and for the url
- [x] catchphrase
- [x] doc text
- [ ] error message text including email
- ~select a shade of green from our theme for the banner background~

[UX sketch](https://github.com/MetabolicAtlas/MetabolicAtlas/files/8813718/ux.pdf) that aims to reuse styles/components:
- [x] homepage banner
- [x] search field
- [x] documentation table of contents (all sections on the same page)
- [x] font styles
- [X] error message when search term is not found
- [x] pages for the different elements that can be searched for should look like the GEM Browser pages (1-2 tables at the top)
- [x] table (but unsure which design to recommend from a technical perspective)

Non-functional requierements:
- [x] decent response time
- [x] store what can be ~150 million lines with at least 50 bits per row (might work even as a single table) can be 7GB
  - there might be wait to condense this in a meaningful way
- [x] pagination and filters
- datasets:
  - [x] main table: see sketch [ux.pdf](https://github.com/MetabolicAtlas/MetabolicAtlas/files/8813718/ux.pdf)
  - [x] reactions.tsv: id, name, definition/equation, cross-references
  - [x] compounds.tsv: id, name(s), cross-references
  - [x] ec.tsv: id, name
 
New issues to create:
- [x] deployment and database handling
- [x] export TSV button: restricted to the results of the current page
- [x] filter on kcat values (min - max)
- [x] approximate search in the landing page
- [x] quick search (multiple suggestions that are based on fuzzy search, will probably require more letters than 2, as in the integrated GEM quick search) restricted to the top say 10 matches
- [x] use annotation data that exists in the suppl data (such as name) in the search
- [x] mapping to integrated models

Ideas for future versions:
- approximate search in the tables (filters)
- dynamic, generic charts to cover distribution of values, that includes min-max filtering
- public API
- expand database with more columns such as the quality of the prediction
- change from IDs to readable names
- get inspired by [RxnMapper](http://rxnmapper.ai)
- autocompletion (a suggestion that continues the partial search)

**Comment by mihai-sysbio** [comment]
All other GotEnzymes-related issues will be gathered under a different epic.
