### ISSUE TITLE
Prep the next MetAtlas release

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1394]
**Please describe the feature**

As a [type of user], I want [an action] so that [a benefit/a value].
As a user, I want Metabolic Atlas to contain up-to-date models.
As a developer, I want Metabolic Atlas to have up-to-date dependencies.
 
**Acceptance Criteria**

- [x] all models updated
- [x] all dependencies updated, where easily doable
- [x] update the development team overview
- [x] The changes are tested on multiple models and browsers
- [x] Tests verifying the changes are added
- [x] The API response is the same as before
- [x] The changes do not affect the deployment
- [x] The changes do not reduce the performance

**Additional context**

**Comment by mihai-sysbio** [comment]
Closed by merging #1396
